### Yash-d configuration file. 

## General configs
title: "Yash-D - Yet another Self Hosted Dashboard" #The title for the head
logo: "logo.svg" 
favicon: "favicon.svg"

## Header config
header:
  enabled: true #Enable or disable header
  type: "transparent" #{bar | transparent}
  title: "YASH-D" #Title that goes in the header
  
services:
  - name: 'Nextcloud'
    icon: '/assets/favicon.svg'
    url: 'https://cloud.blvckhat.dev'
  - name: 'Portainer'
    icon: '/assets/favicon.svg'
    url: 'https://portainer.blvckhat.dev'
  - name: 'Grafana'
    icon: '/assets/favicon.svg'
    url: 'https://monitor.blckhat.dev'
  - name: 'Nginx'
    icon: '/assets/favicon.svg'
    url: 'https://nginx.blvckhat.dev'
  - name: 'Photoprism'
    icon: '/assets/favicon.svg'
    url: 'https://photo.blvckhat.dev'






